[package]
name = "algorithms"
version = "0.1.0"
authors = ["ishowta <ishowta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.19.2"
rand = "0.7.3"
